openapi: 3.0.0
info:
  title: InfraPilot API
  version: 1.0.0
  description: API for InfraPilot DevOps Assistant

servers:
  - url: https://{apiId}.execute-api.{region}.amazonaws.com/{stage}
    variables:
      apiId:
        default: your-api-id
        description: API Gateway ID
      region:
        default: us-east-1
        description: AWS Region
      stage:
        default: prod
        description: API Stage

paths:
  /chat:
    post:
      summary: Send a message to InfraPilot
      operationId: sendMessage
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - message
              properties:
                message:
                  type: string
                  description: User message
                conversation_id:
                  type: string
                  description: Optional conversation ID for continuing a chat
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: Assistant's response
                  conversation_id:
                    type: string
                    description: Conversation ID
                  infrastructure_code:
                    type: string
                    description: Generated infrastructure code (if applicable)
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '500':
          description: Server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

components:
  x-amazon-apigateway-integration:
    type: aws_proxy
    uri: 
      Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${LambdaFunction.Arn}/invocations
    passthroughBehavior: when_no_match
    httpMethod: POST
    contentHandling: CONVERT_TO_TEXT
    timeoutInMillis: 29000